package com.example.wraith55.swipeblok;

import android.app.Activity;
import android.app.Application;
import android.content.Context;
import android.content.DialogInterface;
import android.content.SharedPreferences;
import android.media.Image;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.MotionEvent;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.GridView;
import android.widget.TextView;
import android.widget.Toast;

import org.w3c.dom.Text;

import java.util.ArrayList;
import java.util.Random;
import java.lang.Math;
import java.lang.Object;
import android.os.Handler;
//import java.util.logging.Handler;
import java.util.logging.LogRecord;

import static java.security.AccessController.getContext;


public class MainActivity extends ActionBarActivity {

    GridView gridView;
    static final Random rand = new Random();
    String[] numbers = new String[16];
    String[] numbersOld = new String[16];
    public static final String empty = "()";
    public static int explodeSpot;
    String[] characters = {"1","2","3","4", "5", "6", "7"};
    public boolean gameOver = false;

    Context myContext;
    public static MainActivity activity;
    public int points;
    public int highScore = 0;
    public String target;
    public int difficulty = 4;



    float[] touchData = new float[2];

    /**
     * This is the function called when the activity is created
     * @param savedInstanceState automatically generated by android
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //sets content view to the main activity
        setContentView(R.layout.activity_main);
        activity = this;

        //data structure for handling the pictures
        gridView = (GridView) findViewById(R.id.gridView1);

        //this is to be able to call functions from a static context
        myContext = this.getApplicationContext();
        final Application myApplication = this.getApplication();

        //initializes the game (variables, data structures, etc.)
        startNewGame(gridView);

        //this sets the touch listener on the grid view to pass touch events up to the activity
        gridView.setOnTouchListener(new View.OnTouchListener() {

            @Override
            public boolean onTouch(View v, MotionEvent event) {
                MainActivity.activity.onTouchEvent(event);
                return true;
            }
        });

        //sets up the undo button
        Button undoButton = (Button) findViewById(R.id.undobutton);
        undoButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                MainActivity.activity.undo(activity.gridView);
            }
        });


    }


    /**
     * Whenever the user touches the screen, the on touch listener is called
     * @param event whatever the user did (pushed down, lifted up, moved, etc.)
     * @return a boolean of whether it should be thrown up the stack to higher activities
     */
    public boolean onTouchEvent(MotionEvent event){
        float x, y;
        //checks to see if any squares are left to move to
        if(anyLeft() < 0){
            gameOver = true;
        }

        //returns if gameover has occurred, so the user can't try to move tiles once that screen is up
        if(gameOver){
            return true;
        }

        //if the user presses down, get the initial position of the finger
        if(event.getActionMasked() == MotionEvent.ACTION_DOWN){
            x = event.getX();
            y = event.getY();
            touchData[0] = x;
            touchData[1] = y;
        }

        //once the finger is pulled back up, track x and y to get distance traveled from initial position
        if(event.getActionMasked() == MotionEvent.ACTION_UP){
            x = event.getX();
            y = event.getY();
            float diffX = x - touchData[0];
            float diffY = y - touchData[1];

            //logic for calculating which direction was swiped
            if(Math.abs(diffX) > Math.abs(diffY)){
                if(diffX < 0){
                    //swiped left
                    swipeLeft();
                }
                else{
                    //swiped right
                    swipeRight();
                }
            }
            else{
                if(diffY > 0){
                    //swiped down
                    swipeDown();
                }
                else{
                    //swiped up
                    swipeUp();
                }
            }

        }

        //reinitialize the on touch listener
        gridView.setOnTouchListener(new View.OnTouchListener() {

            @Override
            public boolean onTouch(View v, MotionEvent event) {
                MainActivity.activity.onTouchEvent(event);
                return true;
            }
        });
        return true;
    }

    /**
     * This function handles when the user swipes down
     */
    private void swipeDown(){
        //start off assuming nothing moved
        boolean moved = false;
        //set up a temp numbers array for the undo
        String[] numbersTmp = new String[numbers.length];
        //array copy because setting them to equal each other will just copy the memory location
        numbersTmp = arrayCopy(numbers, numbersTmp);
        //loop through and move whatever squares you can down
        for(int i=8;i>=0;i=i-4){
            for(int j=i;j<i+4;j++){
                //don't move an empty square
                if(numbers[j] == empty) continue;
                //if the square below is empty, move to it
                if(numbers[j+4] == empty){
                    numbers[j+4] = numbers[j];
                    numbers[j] = empty;
                    moved = true;
                }
                //if it's a bomb, explode it
                else if(numbers[j] == characters[characters.length-1]){
                   explode(j);
                   points += 100;
                   moved = true;
                }
                //if the two are the same, remove them both
                else if(numbers[j] == numbers[j+4]){
                    numbers[j] = numbers[j+4] = empty;
                    points += 10;
                    moved = true;
                }

            }
        }
        //only spawn new stuff if user made a legal move
        if(moved == true){
            numbersOld = arrayCopy(numbersTmp,numbersOld);
            spawnNew();
        }
        //always update as that will update the structures and the graphics
        update();

    }

    /**
     * Handles the case of the user swiping up
     */
    private void swipeUp(){
        boolean moved = false;
        String[] numbersTmp = new String[numbers.length];
        numbersTmp = arrayCopy(numbers,numbersTmp);
        //loop through and attempt to move squares up
        //look are swipe down for details on logic
        for(int i=4; i<16;i=i+4){
            for(int j=i;j<i+4;j++){
                if(numbers[j] == empty) continue;
                else if(numbers[j-4] == empty){
                    numbers[j-4] = numbers[j];
                    numbers[j] = empty;
                    moved = true;
                }
                else if(numbers[j] == characters[characters.length-1]){
                    explode(j);
                    points += 100;
                    moved = true;
                }
                else if(numbers[j]==numbers[j-4]){
                    numbers[j] = numbers[j-4] = empty;
                    points += 10;
                    moved=true;
                }

            }
        }

        if(moved == true){
            numbersOld = arrayCopy(numbersTmp, numbersOld);
            spawnNew();
        }
        update();
    }

    /**
     * handles when user swipes right
     */
    private void swipeRight(){
        boolean moved = false;
        String[] numbersTmp = new String[numbers.length];
        numbersTmp = arrayCopy(numbers, numbersTmp);
        //loops through to move all blocks right
        //look at swipeDown() for details on logic
        for(int i=2;i>=0;i--){
            for(int j=i;j<16;j=j+4){
                if(numbers[j] == empty) continue;
                else if(numbers[j+1] == empty){
                    numbers[j+1] = numbers[j];
                    numbers[j] = empty;
                    moved = true;
                }
                else if(numbers[j] == characters[characters.length-1]){
                    explode(j);
                    points += 100;
                    moved = true;
                }
                else if(numbers[j] == numbers[j+1]){
                    numbers[j]=numbers[j+1]=empty;
                    points += 10;
                    moved = true;
                }

            }
        }
        if(moved == true){
            numbersOld = arrayCopy(numbersTmp, numbersOld);
            spawnNew();
        }
        update();
    }

    /**
     * Handles the event when a user swupes left
     */
    private void swipeLeft(){
        boolean moved = false;
        String[] numbersTmp = new String[numbers.length];
        numbersTmp = arrayCopy(numbers, numbersTmp);
        //loops through and moves blocks left
        //look at swipeDown() for details on logic
        for(int i=1;i<4;i++){
            for(int j=i;j<16;j=j+4){
                if(numbers[j] == empty) continue;
                else if(numbers[j-1] == empty){
                    numbers[j-1] = numbers[j];
                    numbers[j]=empty;
                    moved = true;
                }
                else if(numbers[j] == characters[characters.length-1]){
                    explode(j);
                    points += 100;
                    moved = true;
                }
                else if(numbers[j] == numbers[j-1]){
                    numbers[j]=numbers[j-1]=empty;
                    points += 10;
                    moved = true;
                }

            }
        }
        if(moved == true){
            numbersOld = arrayCopy(numbersTmp, numbersOld);
            spawnNew();
        }
        update();
    }

    /**
     * spawns a new tile in an empty square
     * only called when appropriate
      */
    private void spawnNew(){
        //anyLeft checks to see what spots are free
        int addSpot = anyLeft();
        //if it's a negative number, all spots are taken
        if(addSpot<0){
            gameOver();
            return;
        }
        //otherwise spawn a block
        //if bomb=true, the next block will be a bomb
        boolean bomb = false;
        if (rand.nextInt(100) > 90) bomb = true;
        if(bomb){
            numbers[addSpot] = characters[characters.length - 1];
        }
        else{
            numbers[addSpot] = characters[rand.nextInt(characters.length - difficulty)];
        }
        update();

    }

    /**
     * Checks to see the free blocks of the grid, and returns one randomly
     * @return the int position of a free block if there is one, -1 if not
     */
    private int anyLeft(){
        boolean roomLeft = false;
        ArrayList<Integer> freeSpots = new ArrayList<Integer>();
        //loop through and add all free spots to the array list
        for(int i=0; i<numbers.length; i++){
            if(numbers[i] == empty){
                roomLeft = true;
                freeSpots.add(i);
            }
        }
        //as long as there is room left, return one of the free spots
        if(roomLeft){
            return freeSpots.get(rand.nextInt(freeSpots.size()));
        }
        //otherwise return -1, so the caller knows there is no free space
        else return -1;
    }

    /**
     * Updates the data structure and view for the user
     */
    public void update(){

        //update high score if necessary
        if(points > highScore){
            highScore = points;
        }
        //if points are higher than the threshold, up the difficulty
        if(points > (5-difficulty) * 1000 && difficulty > 2) difficulty--;

        setContentView(R.layout.activity_main);

        gridView = (GridView) findViewById(R.id.gridView1);

        //update the level if necessary
        TextView levelView = (TextView) findViewById(R.id.level);
        levelView.setText("Level " + (5-difficulty));

        //update points
        TextView pointView = (TextView)findViewById(R.id.pointText);
        pointView.setText("Points: " + points);

        //update the high score
        TextView highScoreView = (TextView) findViewById(R.id.highscore);
        highScoreView.setText("High score: " + highScore);

        //create the game over screen if necessary
        TextView gameOverView = (TextView)findViewById(R.id.gameover);
        if(gameOver){
            gameOverView.setText("Game Over!");
            gridView.setOnTouchListener(new View.OnTouchListener() {

                @Override
                public boolean onTouch(View v, MotionEvent event) {

                    return true;

                }
            });
        }
        else gameOverView.setText("");

        //update the image adapter
        ImageAdapter adapter = new ImageAdapter(activity);
        adapter.update(numbers);

        gridView.setAdapter(adapter);

    }


    /**
     * explodes a bomb at the given location
     * @param position position to blow bomb
     */
    public void explode(int position){
        boolean up,down,left,right;
        up = down = left = right = true;

        //figure out which positions are legal to blow up (don't go outside the array!)
        if (position + 4 > 15) down = false;
        if(position - 4 < 0) up = false;
        if((position % 4 - 1) < 0) left = false;
        if ((position % 4 + 1) > 3) right = false;

        //set all areas which the bomb affected to empty
        if (up && left) numbers[position - 5] = empty;
        if(up) numbers[position - 4] = empty;
        if(up && right) numbers[position - 3] = empty;
        if(left) numbers[position - 1] = empty;
        if(right) numbers[position + 1] = empty;
        if(down && left) numbers[position + 3] = empty;
        if(down) numbers[position + 4] = empty;
        if(down && right) numbers[position + 5] = empty;
        numbers[position] = empty;

    }

    /**
     * Undo will be called if the user hits the undo button
     * Goes back in time one move but removes user's points by 100
     * @param v the current view
     */
    public void undo(View v){
        points -= 100;
        //don't remove points to negative score
        if (points < 0) points = 0;
        //if there was a gameover, remove it
        gameOver = false;

        //copy from the old array to the new one, effectively going back one timestep
        numbers = arrayCopy(numbersOld, numbers);

        //update the view and data structures
        update();

        //re-initialize the buttons
        Button undoButton = (Button) findViewById(R.id.undobutton);
        undoButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                MainActivity.activity.undo(activity.gridView);
            }
        });

        gridView.setOnTouchListener(new View.OnTouchListener() {

            @Override
            public boolean onTouch(View v, MotionEvent event) {
                MainActivity.activity.onTouchEvent(event);
                return true;
            }
        });

    }

    /**
     * The function to start the new game, initializes variables to correct values
     * @param v
     */
    public void startNewGame(View v){
        //set all numbers to empty
        for(int i=0; i < numbers.length;i++){
            numbers[i] = empty;
        }

        //starting difficulty at 4, variable difficulty is inversely proportional to actual difficulty
        difficulty = 4;

        //spawn a new block in the scope of the difficulty
        numbers[rand.nextInt(16)] = characters[rand.nextInt(characters.length - difficulty)];
        //intialize the undo array
        numbersOld = arrayCopy(numbers, numbersOld);
        //initialize points
        points = 0;

        setContentView(R.layout.activity_main);

        //reset gameOver
        gameOver = false;
        //update the view and data structures
        update();

        //intialize the buttons
        Button newgamebutton = (Button) findViewById(R.id.newgamebutton);
        newgamebutton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                MainActivity.activity.startNewGame(activity.gridView);
            }
        });

        gridView.setOnTouchListener(new View.OnTouchListener() {

            @Override
            public boolean onTouch(View v, MotionEvent event) {
                MainActivity.activity.onTouchEvent(event);
                return true;

            }
        });


    }

    /**
     * called if there is a game over to put up a game over screen
     */
    public void gameOver(){
        gameOver = true;
        update();

    }

    /**
     * copies contents of arr1 to arr2
     * @param arr1
     * @param arr2
     * @return
     */
    public static String[] arrayCopy(String[] arr1, String[] arr2){
        for (int i=0; i<arr1.length;i++){
            arr2[i] = arr1[i];
        }
        return arr2;
    }



    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }


}
